version: "3.9"
services:
  nginx-mycrud:
      container_name: nginx-mycrud
      working_dir: /var/www/html/
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./frontend:/var/www/html
        - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-mycrud:
    container_name: node-mycrud
    image: node:latest
    ports:
     - "9001:9001"
    volumes:
     - ./backend:/application 
     - ./docker-config/node/start_application.sh:/application/start_application.sh
    restart: always
    entrypoint: /application/start_application.sh
    healthcheck:
     test: ["CMD-SHELL", "curl -f http://localhost:9001"]
     interval: 20s
     timeout: 10s
     retries: 3
       
  mysql-mycrud:
    image: mysql:5.7
    container_name: mysql-mycrud
    volumes:
      - ./database:/var/lib/mysql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./docker-config/mysql/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:  
      "MYSQL_DATABASE": "my_crud"
      "MYSQL_ROOT_PASSWORD": "mypass"